engines:
  fixme:
    enabled: true
    checks:
      bug:
        enabled: true
    paths:
     - src/**
     - lib/**
     - bin/**
     - "**.php"
     - "**.pl"
     - "**.pm"
     exclude_paths:
      - "**/*.md"
      - "*.md"
      - "**/*.yml"
      - "*.yml"
  phpcodesniffer:
    enabled: true
  phpmd:
    enabled: true
ratings:
  paths:
  - src/**
  - lib/**
  - bin/**
  - "**.php"
  - "**.pl"
  - "**.pm"
exclude_paths:
- "**/*.md"
- "*.md"
- "**/*.yml"
- "*.yml"