engines:
  fixme:
    enabled: true
    exclude_fingerprints:
    - 8d83e140b70aada8c454a638ba3c4cd0
    - c42b72af850c2590419dfa0bb4d15004
  phpcodesniffer:
    enabled: true
  phpmd:
    enabled: true
exclude_paths:
- "**/*.md"
- "*.md"